name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Deploy
        run: |
          yarn install
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions'
          git remote set-url origin https://${{ secrets.DEPLOY_SITE }}@github.com/babymonitor-ps/babymonitor-ps.github.io.git
          CI=false && cd site && yarn build
#      - uses: enriikke/gatsby-gh-pages-action@v2
#        with:
#          access-token: ${{ secrets.DEPLOY_SITE }}
#          deploy-branch: master